Vstaz 58
hussarcompany/vstazherstve_back pull request #9
Opened 2021-08-11 18:57 UTC by FeelinItNowMrKrabs

Merge pls

2021-08-11 19:05 UTC, grogn requested changes

2021-08-11 19:05 UTC, grogn commented on auth/repository/mongo/user.go
> +package mongo
Пустой файл, зачем?

2021-08-11 19:05 UTC, grogn commented on main.go
> +	client, err = mongo.NewClient(options.Client().ApplyURI("mongodb+srv://Hussar:Hussar1@hussarcluster.cokdm.mongodb.net/test"))
Спрятать кредентиалы

2021-08-11 19:05 UTC, grogn commented on main.go
> +var err error
Зачем глобальный err, если он используется только в main

2021-08-11 19:05 UTC, grogn commented on main.go
> +		log.Fatal(err)
Если не подключились к монге, сервер наверное не должен запускаться вообще?

2021-08-11 19:05 UTC, grogn commented on models/form.go
> +package models
Пустой файл

2021-08-11 19:05 UTC, grogn commented on models/user.go
> +package models
Засквошить коммиты

2021-08-11 19:05 UTC, FeelinItNowMrKrabs commented on auth/repository/mongo/user.go
> +package mongo
Вот почему

2021-08-11 19:05 UTC, FeelinItNowMrKrabs commented on main.go
> +	client, err = mongo.NewClient(options.Client().ApplyURI("mongodb+srv://Hussar:Hussar1@hussarcluster.cokdm.mongodb.net/test"))
нет.

2021-08-11 19:05 UTC, FeelinItNowMrKrabs commented on main.go
> +var err error
мне похуй

2021-08-11 19:05 UTC, FeelinItNowMrKrabs commented on main.go
> +		log.Fatal(err)
ок

2021-08-11 19:06 UTC, FeelinItNowMrKrabs commented on models/form.go
> +package models
так и надо

2021-08-11 19:06 UTC, FeelinItNowMrKrabs commented on models/user.go
> +package models
сам сквоши

2021-08-11 19:06 UTC, FeelinItNowMrKrabs commented
Merge.

2021-08-12 10:47 UTC, FeelinItNowMrKrabs commented on auth/repository/mongo/user.go
> +package mongo
Removed useless files

2021-08-12 10:47 UTC, FeelinItNowMrKrabs commented on main.go
> +	client, err = mongo.NewClient(options.Client().ApplyURI("mongodb+srv://Hussar:Hussar1@hussarcluster.cokdm.mongodb.net/test"))
Will do in next patch with authorisation

2021-08-12 10:48 UTC, FeelinItNowMrKrabs commented on main.go
> +var err error
Changed from global to local scope

2021-08-12 10:48 UTC, FeelinItNowMrKrabs commented on main.go
> +		log.Fatal(err)
Added by making server close on HTTP error

2021-08-12 10:48 UTC, FeelinItNowMrKrabs commented on models/user.go
> +package models
Squashed commits

2021-08-12 12:48 UTC, grogn commented on main.go
> +	client, err = mongo.NewClient(options.Client().ApplyURI("mongodb+srv://Hussar:Hussar1@hussarcluster.cokdm.mongodb.net/test"))
Окей, только лучше сделать для этого новую БД, с новыми учетными данными, потому что это уже в истории коммитов будет

2021-08-12 13:02 UTC, grogn requested changes

2021-08-12 13:02 UTC, grogn commented on models/form.go
> +package models
Он все еще существует

2021-08-12 13:02 UTC, grogn commented on go.mod
> -module vstazherstve_back
История коммитов выглядит плохо, должен быть один или несколько коммитов, у тебя две ветки и мердж-коммит
![image](https://user-images.githubusercontent.com/31772551/129201100-99a0c5a1-9399-4ce6-bf42-bd563cbea3d9.png)

2021-08-12 13:11 UTC, FeelinItNowMrKrabs commented on models/form.go
> +package models
Models/form.go там, но его будем точно использовать пусть живет

2021-08-12 13:12 UTC, FeelinItNowMrKrabs commented on go.mod
> -module vstazherstve_back
Там действительно непонятности вышли, с sourcetree работал и пока не совсем уверенно на нем себя чувствую

2021-08-12 14:54 UTC, closed without merging